<a href="https://colab.research.google.com/github/YousefHanna20/Prediction-of-Product-Sales/blob/main/Use_CDF_to_calculate_probabilities.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/weight-height male-female - weight-height.csv")
df.head()

  Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [2]:
female_height = df.loc[df['Gender'] == 'Female', 'Height']
female_height.head()

5000    58.910732
5001    65.230013
5002    63.369004
5003    64.479997
5004    61.793096
Name: Height, dtype: float64

In [3]:
mean = female_height.mean()
std = female_height.std()
print(mean)
print(std)

63.708773603458006
2.6962840157905594

In [6]:
from scipy.stats import norm

#Question1: Probability of females height between 55.0 and 56.0 .

In [7]:
prob_1 = norm.cdf(56.0, loc = mean, scale=std) - norm.cdf(55.0, loc= mean, scale=std)
print(prob_1)

0.0015055206795372414

#Question2: Probability of females height less than 5 feet(60 inch).

In [8]:
prob_2 = norm.cdf(60.0, loc=mean, scale=std)
print(prob_2)

0.0844862355340375

#Question3: Probability of females height greater than the mean.

In [9]:
prob_3 = norm.cdf(mean, loc=mean, scale=std)
print(prob_3)

0.5

###This one can actually be answered without calculation. A normal distribution is symmetric around its mean, so exactly 50% of the distribution is above the mean and 50% below it.